platform :ios, '13.0'
require_relative '../android/node_modules/react-native/scripts/react_native_pods'

target 'NomadPay' do
  config = use_native_modules!
  use_react_native!(:path => '../android')
end
